### ISSUE TITLE
Google Sign-In Popup Closes Right After Launch

### ISSUE THREAD

**Issue by Mintype** [LernItApp/LernIt#6]
The sign-in button using Google in the login and sign up does not work! It briefly opens a window before closing. I am unsure why this is, but this really does need to be solved!

**Comment by Mintype** [comment]
![image](https://github.com/user-attachments/assets/13889e96-e9f3-41d2-b992-165f9733cb97)
This is the button here!

**Comment by rohan-mehta-sde** [comment]
Hi, "Sign in With Google" button is working fine in my system, just one thing, I'm able to log in even when I never signed up before, other than that, its working as expected, please let me know if I mis-understood the issue

**Comment by Mintype** [comment]
> Hi, "Sign in With Google" button is working fine in my system, just one thing, I'm able to log in even when I never signed up before, other than that, its working as expected, please let me know if I mis-understood the issue.

Is the “Sign in With Google” button working for you at https://lernit.site/ ? It works in my development server but not in the production server. Also, it is normal to be able to Log In with Google if you have not signed up before. They both do the exact same thing.

**Comment by VJ-108** [comment]
The current domain is not authorized for OAuth operations. This will prevent signInWithPopup, signInWithRedirect, linkWithPopup and linkWithRedirect from working. Add your domain (lernit.site) to the OAuth redirect domains list in the Firebase console -> Authentication -> Settings -> Authorized domains tab.

**Comment by Mintype** [comment]
> The current domain is not authorized for OAuth operations. This will prevent signInWithPopup, signInWithRedirect, linkWithPopup and linkWithRedirect from working. Add your domain (lernit.site) to the OAuth redirect domains list in the Firebase console -> Authentication -> Settings -> Authorized domains tab.

Ok yes it works now! Thanks!
